data = { "data" : 
    [
        {
            "product_id": "1516241000002" , 
            "object_id": "102641" , 
            "name": "เมาส์ Razer Viper V2 Pro Wireless Gaming Mouse" , 
            "type": "เกมมิ่ง" , 
            "brand":"Razer" , 
            "price" : 5490  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2022/06/Product/razer-viper-v2-pro-wireless-gaming-mouse-black-icon.jpg"] , 
            "option":"" ,
            "detail": "",
            "promotion":{}
        },    
        {
            "product_id": "1532158000001", 
            "object_id": "94220" , 
            "name": "หูฟัง Logitech G333 In-Ear" , 
            "type": "เกมมิ่ง" , 
            "brand":"Logitech" , 
            "price" : 1690  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2021/03/4-ogitech-G333-In-Ear.jpg?w=256"] , 
            "option":"Black" ,
            "detail": "",
            "promotion":None
        },   
        {
            "product_id": "1516014000001" , 
            "object_id": "39265" , 
            "name": "หูฟัง Razer Hammerhead Pro v.2 In-Ear" , 
            "type": "เกมมิ่ง" , 
            "brand":"Razer" , 
            "price" : 1090  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2018/10/13-HyperX-Cloud-Earbud.jpg"] , 
            "option":"" ,
            "detail": "",
            "promotion":None
        } ,   
        {
            "product_id": "1516124000001" , 
            "object_id": "87686" , 
            "name": "เมาส์ไร้สาย Razer Basilisk X Hyperspeed Wireless Gaming Mouse" , 
            "type": "เกมมิ่ง" , 
            "brand":"Razer" , 
            "price" : 1590  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2019/12/razer-basilisk-x-hyperspeed-wireless-gaming-mouse-icon(1).jpg"] , 
            "option":"" ,
            "detail": "",
            "promotion":None
        }  , 
        {
            "product_id": "1516206000001" , 
            "object_id": "98385" , 
            "name": "หูฟัง Razer Kraken V3 Gaming Headset" , 
            "type": "เกมมิ่ง" , 
            "brand":"Razer" , 
            "price" : 3890  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2021/11/Product/razer-kraken-v3-hypersense-gaming-headset-01.jpg"] , 
            "option":"" ,
            "detail": "",
            "promotion": "abc"
        },
        {
            "product_id": "1965014000001" , 
            "object_id": "105700" , 
            "name": "คีย์บอร์ด Keychron V1 Mechanical Keyboard (EN/TH)" , 
            "type": "เกมมิ่ง" , 
            "brand":"Razer" , 
            "price" : 3990  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2023/01/Product/keychron-v1-mechanical-keyboard-en-th-icon.jpg"] , 
            "option":"Red Switch" ,
            "detail": "",
            "promotion":None
        },
        {
            "product_id": "1859015000001" , 
            "object_id": "93174" , 
            "name": "เมาส์ไร้สาย Glorious Model O Wireless Gaming Mouse" , 
            "type": "เกมมิ่ง" , 
            "brand":"Glorious" , 
            "price" : 3590  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2020/12/glorious-model-o-wireless-gaming-mouse-black-icon.jpg"] , 
            "option":"Black" ,
            "detail": "",
            "promotion":None
        },
        {
            "product_id": "1532129000001" , 
            "object_id": "89698" , 
            "name": "เมาส์ Logitech G102 LIGHTSYNC Gaming Mouse" , 
            "type": "เกมมิ่ง" , 
            "brand":"Logitech" , 
            "price" : 990  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2020/06/logitech-g102-lightsync-gaming-mouse-black-icon.jpg"] , 
            "option":"Black" ,
            "detail": "",
            "promotion":None
        },
        {
            "product_id": "1532181000001" , 
            "object_id": "96797" , 
            "name": "หูฟัง Logitech G435 Lightspeed Gaming Wireless Headphone" , 
            "type": "เกมมิ่ง" , 
            "brand":"Logitech" , 
            "price" : 2590  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2022/02/Product/2-Logitech-G435-Lightspeed-Gaming-Wireless-Headphone.jpg"] , 
            "option":"Black and Neon Yellow" ,
            "detail": "",
            "promotion":None
        },
        {
            "product_id": "1740025000001" , 
            "object_id": "97305" , 
            "name": "หูฟัง SoundPeats Air3 True Wireless" , 
            "type": "หูฟัง" , 
            "brand":"SoundPEATS" , 
            "price" : 1659  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2021/10/soundpeats-air3-true-wireless-black-icon.jpg"] , 
            "option":"Black" ,
            "detail": "",
            "promotion":None
        },
        {
            "product_id": "1516199000001" , 
            "object_id": "96432" , 
            "name": "หูฟังไร้สาย Razer Hammerhead True Wireless 2nd Gen" , 
            "type": "หูฟัง" , 
            "brand":"Razer" , 
            "price" : 2290  , 
            "quantity" : 20 , 
            "image" : ["https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2021/08/hammerhead%20TWS%202%20gen.jpg"] , 
            "option":"" ,
            "detail": "",
            "promotion":None
        }
    ]
}